import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({ subsets: ["latin"], weight: ["300", "600", "800"] });

import NavMenu from "@/components/Menu/NavMenu";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${poppins.className} antialiased w-full `}>
                <NavMenu>{children}</NavMenu>
            </body>
        </html>
    );
}
